// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJEJFUpK5R5yu58Jwjv0n0DTHzPs2Voxc',
    appId: '1:418872342436:web:9660e5e60093180fc6b331',
    messagingSenderId: '418872342436',
    projectId: 'cook-off-eb9e7',
    authDomain: 'cook-off-eb9e7.firebaseapp.com',
    storageBucket: 'cook-off-eb9e7.appspot.com',
    measurementId: 'G-1JC22382RQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGzHY_kqi6whybl-SkyS5MVpdQ5PYOrrA',
    appId: '1:418872342436:android:ade36baf5ad2d832c6b331',
    messagingSenderId: '418872342436',
    projectId: 'cook-off-eb9e7',
    storageBucket: 'cook-off-eb9e7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMpSlAPjColdnX9Di0WuGaRat7Z6ONg0U',
    appId: '1:418872342436:ios:e49d023c5551a13fc6b331',
    messagingSenderId: '418872342436',
    projectId: 'cook-off-eb9e7',
    storageBucket: 'cook-off-eb9e7.appspot.com',
    iosBundleId: 'com.example.cookOff',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMpSlAPjColdnX9Di0WuGaRat7Z6ONg0U',
    appId: '1:418872342436:ios:f9fd22da8c83a08fc6b331',
    messagingSenderId: '418872342436',
    projectId: 'cook-off-eb9e7',
    storageBucket: 'cook-off-eb9e7.appspot.com',
    iosBundleId: 'com.example.cookOff.RunnerTests',
  );
}
